spring.application.name=UserAuthenication
spring.datasource.url=jdbc:mysql://localhost:3306/auth_project
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sigt12tshi@wshu.net
spring.mail.password=aSs_y0L%l_!(i+

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8081